# webapp/webapp/settings.py

"""
Django settings for webapp project.
"""

# Removed unused import of os since it was not needed.
# import os

DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    # Add your other apps here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Add your other middleware here
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # Add additional context processors if needed
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files settings
STATIC_URL = '/static/'

# Example dictionary with correct spacing around colons
EXAMPLE_SETTINGS = {
    'option1': True,
    'option2': False,
    'option3': None,
    'option4': 'A string value'
}

# Long string settings broken into multiple lines to meet the 79-character limit.
LONG_TEXT = (
    "This is a long text that is intentionally broken into multiple lines "
    "to comply with PEP8 guidelines on maximum line length."
)

ANOTHER_LONG_TEXT = (
    "Another example of a long string that has been split properly to avoid "
    "line length issues in the settings file."
)
